module.exports = {
  wifeName: 'Denna',
  wifeFullName: 'Denna Erdina S.Ak',
  wifeFullNameCaption: 'Putri ketiga dari Bapak Nana Sobiyana & Ibu Ernida',
  wifeFamily1: 'Nana Sobiyana',
  wifeFamily2: 'Ernida',
  husbandName: 'Ilham',
  husbandFullName: 'Ilham Yudatama S.Kom',
  husbandFullNameCaption: 'Putra ketiga dari Bapak H. Kasiyo & Ibu Hj. Wahyu Wasiyati S.Pd',
  husbandFamily1: 'H. Kasiyo',
  husbandFamily2: 'Hj. Wahyu Wasiyati S.Pd',
  day: 'Ahad',
  date: '29 November 2020',
  address1: 'Kawasan industri Kota Bukit Indah sektor B',
  address2: 'Kecamatan Cikampek',
  address3: 'Cikampek',
  address4: 'Jawa Barat',
  address5: '43173',
  addressLocation: 'https://goo.gl/maps/3s4ufwUYGmpR5hs16',
}
